#
# handlers used on the cockroach db node
#
- name: start cockroach
  become: true
  systemd:
    name: cockroach
    state: started

- name: stop cockroach
  become: true
  systemd:
    name: cockroach
    state: stopped

