#
# tasks to start the cluster nodes
#
- name: start the cluster nodes
  gce:
    instance_names: "{{ hostvars[item]['gce_name'] }}"
    state: started
    zone: "{{ hostvars[item]['gce_zone'] }}"
  with_items: "{{ groups['tag_cockroachdb-cluster-node'] }}"
