- name: terminate the cluster nodes
  gce:
    instance_names: "cockroachdb-cluster-node-{{ item }}"
    state: absent
    zone: "{{ [item | int % 2] | map('extract', [zones.europe, zones.us]) | list | join('')}}"
  with_sequence: count="{{ num_cluster_nodes }}" format="%02d"

- name: terminate firewall rule
  gce_net:
    name: "{{ vpc_name }}"
    fwname: "allow-ssh-ingress"
    state: absent

- name: terminate the subnets
  gce_net:
    name: "{{ vpc_name }}"
    subnet_name: "{{ item.subnet_name }}"
    subnet_region: "{{ item.subnet_region }}"
    state: absent
  with_items:
    - { subnet_name: "{{ subnets.name.europe }}", subnet_region: "{{ subnets.region.europe }}", ipv4_range: "{{ subnets.ipv4.europe }}" }
    - { subnet_name: "{{ subnets.name.us }}", subnet_region: "{{ subnets.region.us }}", ipv4_range: "{{ subnets.ipv4.us }}"}

- name: pause a couple of seconds 
  pause: seconds=10

- name: terminate the virtual private network
  gce_net:
    name: "{{ vpc_name }}"
    state: absent
