#
# tasks to terminate the cluster
#
- name: terminate the cluster nodes
  gce:
    instance_names: "cockroachdb-cluster-node-{{ item }}"
    state: absent
    zone: "{{ [item | int % 2] | map('extract', [zones.europe, zones.us]) | list | join('')}}"
  with_sequence: count="{{ num_cluster_nodes }}" format="%02d"

- name: terminate firewall rules
  gce_net:
    name: "{{ vpc_name }}"
    fwname: "{{ item }}"
    state: absent
  with_items:
    - allow-ssh-ingress
    - "{{ vpc_name }}-default-allow-internal"

- name: terminate the subnets
  gce_net:
    name: "{{ vpc_name }}"
    subnet_name: "{{ item.subnet_name }}"
    subnet_region: "{{ item.subnet_region }}"
    state: absent
  with_items:
    - { subnet_name: "{{ subnets.name.europe }}", subnet_region: "{{ subnets.region.europe }}", ipv4_range: "{{ subnets.ipv4.europe }}" }
    - { subnet_name: "{{ subnets.name.us }}", subnet_region: "{{ subnets.region.us }}", ipv4_range: "{{ subnets.ipv4.us }}"}

- name: "pause for {{ pause_interval }} secs before terminating the VPC"
  pause: 
    seconds: "{{ pause_interval }}" 

- name: terminate the virtual private network
  gce_net:
    name: "{{ vpc_name }}"
    state: absent
