# the filename and download url of the cockroachdb distribution
cockroach_distribution:
  filename: cockroach-v1.1.6.linux-amd64.tgz
  url: "https://binaries.cockroachdb.com/cockroach-v1.1.6.linux-amd64.tgz"

cockroach_node:
  datadir: /var/data/cockroachdb
  logdir: /var/log/cockroachdb
  # the port on which the cockroach API is exposed
  port: 26257
  # the port on which the admin GUI is exposed
  http_port: 8080

# the local directory where generated certificates for cockroach 
# are stored
local_certs_dir: certs
# the local directory where generated keys for cockroach are stored
local_keys_dir: keys
# the remote directory where certificates are deployed to
remote_certs_dir: /etc/cockroach/certs

# the list of users for which we generate client certificates
client_users:
  - root