#
# installs docker-ce on the current host
#
- name: install required packages
  become: true
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: add docker key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add apt repository for docker
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
    state: present

- name: install docker
  become: true
  apt:
    name: docker-ce
    update_cache: yes
    state: latest

