#
# play to create the cluster including the network, the disks,
# and the compute engine nodes
#
- hosts: localhost
  gather_facts: false
  strategy: free

  vars:
    num_cluster_nodes: 2

  roles:
    - import_role:
        name: cluster
        from_tasks: create
        
  post_tasks:
    - shell: ./gce.py --refresh-cache
    - meta: refresh_inventory

# 
# play to provision the cluster nodes
#
- hosts: "tag_cockroachdb-cluster-node"
  gather_facts: false
  strategy: free

  pre_tasks:
    - include_role:
        name: sshserver
        from_tasks: wait-for-ssh

  roles:
    - ubuntu-node
    - cockroach-node