#
# play to create the cluster including the network, the disks,
# and the compute engine nodes
#
- name: create cloud infrastructure
  hosts: localhost
  gather_facts: false

  vars_prompt:
    name: num_cluster_nodes
    prompt: "Number of cluster nodes (n>=2, choose an even number) [default=2]"
    default: 2
    private: no

  tasks:
    - include_role:
        name: cluster
        tasks_from: create-network

    - include_role:
        name: cluster
        tasks_from: create
        
  post_tasks:
    - shell: ./gce.py --refresh-cache
    - meta: refresh_inventory

# 
# play to provision the cluster nodes
#
- name: provision and configure cockroach
  hosts: tag_cockroachdb-cluster-node
  # disable. strange behaviour. Sometimes can't find or access a directory
  # on localhost
  #strategy: free
  gather_facts: false

  pre_tasks:
    - include_role:
        name: sshserver
        tasks_from: wait-for-ssh

  tasks:
    - name: update the operating system
      include_role:
        name: ubuntu-node

    - name: install and configure cockroach 
      include_role:
        name: cockroach-node

    - name: generate and deploy the certificates
      block:
        - include_role:
            name: cockroach-node
            tasks_from: ca-certificate
        - include_role:
            name: cockroach-node
            tasks_from: node-certificates
        - include_role:
            name: cockroach-node
            tasks_from: client-certificate

    - name: restart cockroach service
      shell: /bin/true
      notify: restart cockroach
