#
# play to create the cluster including the network, the disks,
# and the compute engine nodes
#
- hosts: localhost
  gather_facts: false

  vars:
    num_cluster_nodes: 2

  roles:
    - cluster

  post_tasks:
    - shell: ./gce.py --refresh-cache
    - meta: refresh_inventory

# 
# play to provision the cluster nodes
#
- hosts: "tag_cockroachdb-cluster-node"
  gather_facts: false

  pre_tasks:
    - name: wait for SSH to come up
      wait_for: 
        delay: 1 
        host: "{{ ansible_ssh_host }}" 
        port: 22 
        state: started 
        timeout: 360

  roles:
    - ubuntu-node
    - cockroach-node