#
# play to start the cluster
#
- hosts: localhost
  gather_facts: false

  vars:
    num_cluster_nodes: 2

  roles:
    - {role: cluster, action: "start"}

  post_tasks:
    - shell: ./gce.py --refresh-cache
    - meta: refresh_inventory

# 
# play to provision the cluster nodes
# TODO: start cockroachdb
- hosts: "tag_cockroachdb-cluster-node"
  gather_facts: false


 