
# 
# play to stop the cockroachdb software
- hosts: "tag_cockroachdb-cluster-node"
  gather_facts: false

  tasks:
    - name: stop cockroach
      systemd:
        name: cockroach
        state: stopped
      become: true
#
# play to stop the cluster nodes
#
- hosts: localhost
  gather_facts: false

  vars:
    num_cluster_nodes: 2

  roles:
    - {role: cluster, action: "stop"} 