
# 
# play to stop the cockroachdb software
#
- hosts: tag_cockroachdb-cluster-node
  gather_facts: false
  strategy: free

  tasks:
    - include_role:
        name: cockroach-node
        tasks_from: stop
#
# play to stop the cluster nodes
#
- hosts: localhost
  gather_facts: false
  strategy: free

  tasks:
    - name: "stop node"
      include_role:
        name: cluster
        tasks_from: stop
