#
# play to terminate the cluster
#
- hosts: localhost
  gather_facts: false
  # don't use free strategy. play relies on module 'pause'
  # which is not compatible with the free strategy
  # strategy: free   

  vars_prompt:
    name: num_cluster_nodes
    prompt: "Number of cluster nodes in the cluster [default=2]"
    default: 2

  tasks:
    - include_role:
        name: cluster
        tasks_from: terminate
