#
# tasks to to install the cockroach distribution
#
- name: get the coackroach distribution
  get_url:
    url: "{{ cockroach_distribution.url }}"
    dest: "/tmp/{{ cockroach_distribution.filename }}"

- name: unarchive it 
  unarchive:
    remote_src: true
    src: "/tmp/{{ cockroach_distribution.filename }}"
    dest: /usr/local
  become: true

- name: create a symlink for the coachroach distribution
  file:
    src: "/usr/local/{{ (cockroach_distribution.filename | splitext)[0] }}"
    dest: /usr/local/cockroach
    state: link
  become: true

- name: create a symlink to the coachroach binary
  file:
    src: /usr/local/cockroach/cockroach
    dest: /usr/local/bin/cockroach
    state: link
  become: true

- name: create the data and log directories
  file:
    path: "{{ cockroach_node.logdir }}"
    state: directory
    mode: 0755
  become: true
  with_items:
    - "{{ cockroach_node.datadir }}"
    - "{{ cockroach_node.logdir }}"

- name: install systemd service file for cockroach service
  template:
    src: cockroach.service.j2
    dest: /etc/systemd/system/cockroach.service
  become: true

- name: trigger starting of cockroach db
  shell: /bin/true
  notify: start cockroach
