#
# tasks to create the certificates for the cluster nodes
#

- name: ensure local directories for keys and certificates exist
  file: 
    path: "{{ item }}"
    state: directory
    mode: 0700
  with_items:
    - "{{ local_certs_dir }}"     # the directory with the generated certificates
    - "{{ local_keys_dir }}"      # the directory with the generated keys 

- name: create node key and certificate
  local_action: shell cockroach cert create-node       \
        "{{ gce_private_ip }}"                         \
        "{{ gce_public_ip }}"                          \
        localhost                                      \
        127.0.0.1                                      \
        --overwrite                                    \
        --certs-dir={{ local_certs_dir }}              \
        --ca-key={{ local_keys_dir }}/ca.key

- name: create remote certificate directory
  become: true
  file:
    path: /etc/cockroach/certs
    state: directory

- name: upload ca key
  become: true
  copy:
    src: keys/ca.key
    dest: "{{ remote_certs_dir }}"
    mode: 0700  

- name: upload node certificate and node key
  become: true
  copy:
    src: "{{ item }}"
    dest: "{{ remote_certs_dir }}"
    mode: 0700  
  with_items:
    - certs/node.crt
    - certs/node.key

- name: remove local node certificate and node key
  local_action: file path="{{ item }}" state=absent
  with_fileglob:
    - "{{ local_certs_dir }}/node.*"
